### ISSUE TITLE
Area requirement not being used

### ISSUE THREAD

**Issue by rg-jinwood** [letmeproperty/CRM#29]
There seems to be an issue with "area" requirement not being picked up in the CRM.
A-IxVlhDAGsa
This app is an external customer that registered this evening, calling applications through swagger returns the following:

```[
  {
    "RequirementReference": "iTe8EZqeU6",
    "RequirementType": "Number Of Bedrooms",
    "Value": "2"
  },
  {
    "RequirementReference": "H90CaLmBoq",
    "RequirementType": "Price From",
    "Value": "300"
  },
  {
    "RequirementReference": "E2EEU8fIX9",
    "RequirementType": "Price To",
    "Value": "1200"
  },
  {
    "RequirementReference": "sUi1zMrDtw",
    "RequirementType": "Area",
    "Value": "GU"
  }
]
```

But the CRM matche the app to all areas.

**Comment by rg-jonathantansey** [comment]
All seems to be pulling through for me!

<img width="409" alt="screen shot 2015-11-05 at 08 10 19" src="https://cloud.githubusercontent.com/assets/13765558/10963006/ba735046-8394-11e5-9e11-9eeb17623415.png">
<img width="872" alt="screen shot 2015-11-05 at 08 11 00" src="https://cloud.githubusercontent.com/assets/13765558/10963010/c4661750-8394-11e5-98de-05fdac806e77.png">
