### ISSUE TITLE
Events not being displayed in CRM

### ISSUE THREAD

**Issue by rg-jinwood** [letmeproperty/CRM#42]
Example:

http://letme-crm.azurewebsites.net/?ApplicationReference=A-0hXDHHMsuE

Event - https://letme-events.azurewebsites.net:443/api/events/application/A-0hXDHHMsuE

**Comment by rg-jonathantansey** [comment]
Event's were being searched for on a per customer basis as customer was null they were not being picked up. I'll change it so that all events are visible on the feed for all customers

**Comment by rg-jonathantansey** [comment]
Now showing http://letme-crm.azurewebsites.net/?ApplicationReference=A-0hXDHHMsuE
