### ISSUE TITLE
Record Access Events

### ISSUE THREAD

**Issue by rg-kristianwilson** [letmeproperty/CRM#43]
Whenever an agent opens an application through the CRM we need to record an "Access Event" in the events system probably after a configurable delay to make sure they viewed the case. This will be used to work out notifications on caslists in future.

**Comment by rg-jonathantansey** [comment]
@rg-kristianwilson following example is causing a 500 error 

```Javascript
{
        Owner: profile.name, //"Jonathan Tansey"
        EventType: "Access Event",
        ApplicationReference: applicationReference, //"A-R5lHIzCyb0"
        EventDescription: "Access Event",
        EventDetail: "Access Event"
    }
```
What's the correct format for raising an Access event?

**Comment by rg-kristianwilson** [comment]
This format is correct, there was an error with the mapping configuration within events which meant that the date created was being passed as  null.
