### ISSUE TITLE
Unable to save a number via CRM

### ISSUE THREAD

**Issue by rg-jinwood** [letmeproperty/CRM#70]
https://letme-crm.azurewebsites.net/?ApplicationReference=A-OOeGh8EfRR
07964123963 

Saving through CRM fails with a 500 error from apps

`Request URL:https://letme-applications.azurewebsites.net/api/applications/A-OOeGh8EfRR/customers/C-A7zREkaSiO/telephonenumbers
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:104.46.61.116:443`

Saving manually via swagger works fine.

**Comment by rg-jonathantansey** [comment]
There is already another application with that phone number cancelling that application allows you to add the number
