### ISSUE TITLE
Property Lease Dates

### ISSUE THREAD

**Issue by rg-johnhunter** [letmeproperty/CRM#88]
There is a new DealType enum in Properties:
1 = PayUpfront [Description] = "Pay Upfront"
2 = PayWhenRented [Description] = "Pay When Rented"

When the LetMe button is clicked get the value of this enum from the existing call to GetProperty:

Use the following logic when POSTing a property to PropertyBook;
DealType = 1 ... set PropertyStartDate & PropertyEndDate to the same as TenancyStartDate & TenancyEndDate

DealType = 2 ... set PropertyStartDate & PropertyEndDate to the dates returned in the previous call to GetProperty

Ta

**Comment by rg-jonathantansey** [comment]
no longer required
